version: '2.1'

services:
    db:
        image: arminc/clair-db:latest
        restart: on-failure
        healthcheck:
            test: nc -z db 5432
            interval: 1s
            retries: 20

    clair:
        image: arminc/clair-local-scan:latest
        links:
        - db:postgres
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure
        healthcheck:
            test: nc -z clair 6060 && nc -z clair 6061
            interval: 1s
            retries: 20

    scanner:
        image: quay.io/usr42/clair-container-scan:latest
        links:
        - clair
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            clair:
                condition: service_healthy
