version: '3.5'

services:
  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: stellio-kafka
    ports:
      - 29092:29092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./config/stellio/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"

  postgres:
    image: stellio/stellio-timescale-postgis:14-2.9.1-3.3
    container_name: stellio-postgres
    environment:
      - POSTGRES_USER=stellio
      - POSTGRES_PASS=stellio_password
      - POSTGRES_DBNAME=stellio_search,stellio_subscription
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,timescaledb,pgcrypto
      - ACCEPT_TIMESCALE_TUNING=TRUE
    ports:
      - 5432:5432
    volumes:
      - stellio-postgres-storage:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U stellio"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  api-gateway:
    container_name: stellio-api-gateway
    image: stellio/stellio-api-gateway:latest-dev
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080

  search-service:
    container_name: stellio-search-service
    image: stellio/stellio-search-service:latest-dev
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres/stellio_search
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres/stellio_search
      - SPRING_R2DBC_USERNAME=stellio
      - SPRING_R2DBC_PASSWORD=stellio_password
      - APPLICATION_AUTHENTICATION_ENABLED=false
    ports:
      - 8083:8083
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  subscription-service:
    container_name: stellio-subscription-service
    image: stellio/stellio-subscription-service:latest-dev
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres/stellio_subscription
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres/stellio_subscription
      - SPRING_R2DBC_USERNAME=stellio
      - SPRING_R2DBC_PASSWORD=stellio_password
      - APPLICATION_AUTHENTICATION_ENABLED=false
      - APPLICATION_ENTITY_SERVICE_URL=http://search-service:8083
      - APPLICATION_STELLIO_URL=http://localhost:8080
    ports:
      - 8084:8084
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  stellio-postgres-storage:
