version: '3.5'

services:

    wirecloud:
        image: fiware/wirecloud:latest
        container_name: fiware-wirecloud
        hostname: wirecloud
        ports:
            - "8000:8000" # localhost:8000
        networks:
          default:
            ipv4_address: 172.18.1.10

        restart: always
        depends_on:
            - keyrock
            - elasticsearch
            - memcached
            - postgres-db
        environment:
            - DEBUG=True
            - DEFAULT_THEME=wirecloud.defaulttheme
            - DB_HOST=postgres-db
            - DB_PASSWORD=wirepass   # Change this password!
            - FORWARDED_ALLOW_IPS=*
            - ELASTICSEARCH2_URL=http://elasticsearch:9200/
            - MEMCACHED_LOCATION=memcached:11211
            - FIWARE_IDM_PUBLIC_URL=http://localhost:3005
            - FIWARE_IDM_SERVER=http://172.18.1.5:3005
            - SOCIAL_AUTH_FIWARE_KEY=wirecloud-dckr-site-0000-00000000000
            - SOCIAL_AUTH_FIWARE_SECRET=wirecloud-docker-000000-clientsecret
        volumes:
            - wirecloud-data:/opt/wirecloud_instance/data
            - wirecloud-static:/var/www/static

    keyrock:
        image: fiware/idm:latest
        container_name: fiware-keyrock
        hostname: keyrock
        networks:
          default:
            ipv4_address: 172.18.1.5
        depends_on:
            - mysql-db
        ports:
            - "3005:3005" # localhost:3005
            - "3443:3443" # localhost:3443
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql-db
            - IDM_DB_PASS_FILE=/run/secrets/my_secret_data
            - IDM_DB_USER=root
            - IDM_HOST=http://localhost:3005
            - IDM_PORT=3005
            - IDM_ADMIN_USER=alice
            - IDM_ADMIN_EMAIL=alice-the-admin@test.com
            - IDM_ADMIN_PASS=test
        healthcheck:
            test: curl --fail -s http://localhost:3005/version || exit 1

    # Databases

    postgres-db:
        image: postgres
        hostname: postgres-db
        container_name: db-postgres
        restart: always
        ports:
          - "5432:5432"
        networks:
          default:
            ipv4_address: 172.18.1.13
        environment:
            - POSTGRES_PASSWORD=wirepass   # Change this password!
        volumes:
            - postgres-db:/var/lib/postgresql/data

    mysql-db:
        restart: always
        image: mysql:5.7
        hostname: mysql-db
        container_name: db-mysql
        expose:
          - "3306"
        ports:
          - "3306:3306" # localhost:3306
        networks:
          default:
            ipv4_address: 172.18.1.6
        environment:
          - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/my_secret_data"
          - "MYSQL_ROOT_HOST=172.18.1.5" # Allow Keyrock to access this database
        volumes:
          - mysql-db:/var/lib/mysql

    # Other services

    elasticsearch:
        image: elasticsearch:2.4
        container_name: wc-elasticsearch
        hostname: elasticsearch
        ports:
            - "9200:9200"
        networks:
          default:
            ipv4_address: 172.18.1.12

        restart: always
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        command: elasticsearch -Des.index.max_result_window=50000

    memcached:
        image: memcached:1
        container_name: wc-memcached
        hostname: memcached
        ports:
            - "11211:11211"
        networks:
          default:
            ipv4_address: 172.18.1.11

        restart: always
        command: memcached -m 2048m


networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mysql-db: ~
  postgres-db: ~
  elasticsearch-data: ~
  wirecloud-static: ~
  wirecloud-data: ~
