version: "3.5"
services:
  # Draco is configured to write context data to Mongo-DB, PostgeSQL and MySQL
  draco:
    image: ging/fiware-draco:latest
    hostname: draco
    container_name: fiware-draco
    networks:
      - default
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    expose:
      - "5050"
      - "9090"
    ports:
      - "9090:9090" # localhost:9090
      - "5050:5050"
    healthcheck:
      test: curl --fail -s http://draco:9090/nifi-api/system-diagnostics || exit 1
      start_period: 1m