#!/usr/bin/env /usr/bin/python3.8
# -*- coding: utf-8 -*-
##
# Copyright 2017 FIWARE Foundation, e.V.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
##

from smtplib import SMTP
from logging import info, debug, exception
from logging import _nameToLevel as nameToLevel
from base64 import b64encode
from urllib.request import urlopen, Request
from urllib.error import URLError
from urllib.parse import urlencode
from json import loads
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from config.settings import ACCESS_TOKEN, REFRESH_TOKEN, CLIENT_ID, CLIENT_SECRET, SENDER, \
                            GOOGLE_ACCOUNTS_BASE_URL, __version__
from logging import INFO, DEBUG
from config.config_logging import LoggingConf
from argparse import ArgumentParser, FileType
from urllib3 import disable_warnings
from urllib3.exceptions import InsecureRequestWarning

import ssl


__author__ = 'fla'


class Emailer(LoggingConf):
    def __init__(self, loglevel=INFO):
        super(Emailer, self).__init__()
        self._sender = SENDER

        # My OAuth2 access token
        self.access_token = ACCESS_TOKEN

        # My OAuth2 refresh token
        self.refresh_token = REFRESH_TOKEN

        # The client_id used in my tests
        self.client_id = CLIENT_ID

        # The client_secret of my gmail account
        self.client_secret = CLIENT_SECRET

        # The URL root for accessing Google Accounts.
        self.GOOGLE_ACCOUNTS_BASE_URL = GOOGLE_ACCOUNTS_BASE_URL

        # The signature of my emails
        self.signature = '\n\n------------------------' + \
                         '\nFernando Lopez' + \
                         '\nInterim FIWARE Security Analyst'

        # Log level
        self.log_level = loglevel

        # Allow unverified SSL Context
        ssl._create_default_https_context = ssl._create_unverified_context

    def generate_oauth2string(self, username, base64_encode=True):
        """Generates an IMAP OAuth2 authentication string.

        See https://developers.google.com/google-apps/gmail/oauth2_overview

        Args:
            username: the username (email address) of the account to authenticate
            base64_encode: Whether to base64-encode the output.

        Returns:
            The SASL argument for the OAuth2 mechanism.
        """
        auth_string = 'user=%s\1auth=Bearer %s\1\1' % (username, self.access_token)

        if base64_encode:
            auth_string = b64encode(auth_string.encode())

        return auth_string

    def accounts_url(self, command):
        """Generates the Google Accounts URL.

        Args:
            command: The command to execute.

        Returns:
            A URL for the given command.
        """
        return '%s/%s' % (self.GOOGLE_ACCOUNTS_BASE_URL, command)

    def refresh_old_token(self):
        """Obtains a new token given a refresh token.

        See https://developers.google.com/accounts/docs/OAuth2InstalledApp#refresh

        Returns:
            The decoded response from the Google Accounts server, as a dict. Expected
            fields include 'access_token', 'expires_in', and 'refresh_token'.
        """
        data = dict()
        data['client_id'] = self.client_id
        data['client_secret'] = self.client_secret
        data['refresh_token'] = self.refresh_token
        data['grant_type'] = 'refresh_token'
        request_url = self.accounts_url('o/oauth2/token')

        data = urlencode(data)
        data = data.encode('utf-8')  # data should be bytes
        req = Request(request_url, data)

        try:
            resp = urlopen(req)
            respdata = resp.read()

            self.access_token = loads(respdata)['access_token']
        except URLError:
            debug("Unable to get a new refreshed token ...")

    def _deliver(self, msg):
        server = SMTP('smtp.gmail.com', 587)
        try:
            info("[+] Connecting To Mail Server.")

            if self.log_level == DEBUG:
                server.set_debuglevel(2)
            else:
                server.set_debuglevel(0)

            server.ehlo()

            debug("[+] Starting Encrypted Session.")
            server.ehlo()
            server.starttls()

            debug("[+] Logging Into Mail Server.")
            oauth_string = self.generate_oauth2string(username=self._sender)
            (code, message) = server.docmd('AUTH', 'XOAUTH2 ' + oauth_string.decode())

            if code == 334:
                # The token is invalid an should be refresh
                debug("[+] oAuth2 access token expired, refreshing it.")
                self.refresh_old_token()

                server.close()
                server = SMTP('smtp.gmail.com', 587)

                if self.log_level == DEBUG:
                    server.set_debuglevel(2)
                else:
                    server.set_debuglevel(0)

                server.ehlo()

                debug("[+] Starting Encrypted Session.")
                server.ehlo()
                server.starttls()

                debug("[+] Logging Into Mail Server again.")
                oauth_string = self.generate_oauth2string(username=self._sender)
                server.docmd('AUTH', 'XOAUTH2 ' + oauth_string.decode())

            debug("[+] Sending Mail.")
            server.sendmail(self._sender, msg['To'], msg.as_string())

            server.close()
            info("[+] Mail Sent Successfully to {}.".format(msg['To']))

        except Exception as e:
            exception(e)
            exception("[-] Sending Mail Failed.")

    def send(self, messages, deliver=False):
        for n, item in enumerate(messages):
            info('#{}, Key:{}, To:{}, Summary:{}'
                 .format(n, item['issue'].key, item['displayname'].encode('utf-8'), item['summary']))

            debug('{} \n {}'.format(item['subject'], item['body']))

            if deliver:
                self.send_msg(item['email'], item['subject'], item['body'])

    def send_msg(self, to, subject, body='', deliver=True):
        msg = MIMEText(body + self.signature)

        msg['From'] = self._sender
        msg['To'] = to
        msg['Subject'] = subject

        if deliver:
            self._deliver(msg)

    def send_adm_msg(self, subject, body, deliver=True):
        msg = MIMEText(body + self.signature)

        msg['From'] = self._sender
        msg['To'] = self._sender
        msg['Subject'] = 'FIWARE: Reminders: ' + subject

        if deliver:
            self._deliver(msg)

    def send_html_adm_msg(self, subject, body, deliver=True):
        msg = MIMEMultipart('alternative')

        msg['From'] = self._sender
        msg['To'] = self._sender
        msg['Subject'] = 'FIWARE: Reminders: ' + subject

        part1 = MIMEText(body, 'html')
        part2 = MIMEText(self.signature, 'plain')

        msg.attach(part1)
        msg.attach(part2)

        if deliver:
            self._deliver(msg)

    def send_msg_attachment(self, to, subject, body, infile, deliver=True):
        msg = MIMEMultipart()

        msg['From'] = self._sender
        msg['To'] = to
        msg['Subject'] = subject
        msg.attach(MIMEText(body + self.signature))

        for i in range(0, len(infile)):
            filemsg = MIMEApplication(infile[i].read(), _subtype="xlsx")
            infile[i].close()

            filemsg.add_header('Content-Disposition', 'attachment; filename = {}'.format(infile[i].name))
            msg.attach(filemsg)

        if deliver:
            self._deliver(msg)


def init():
    parser = ArgumentParser(prog='mail', description='Email a message to a destination using GMail account.')

    parser.add_argument('-s',
                        '--subject',
                        type=str,
                        required=True,
                        dest='subject',
                        help='Subject of the email.')

    parser.add_argument('-t',
                        '--to',
                        type=str,
                        required=True,
                        dest='to',
                        help='Destination email address of the email.')

    parser.add_argument('-a',
                        '--attach',
                        nargs='?',
                        type=FileType('r'),
                        required=False,
                        action='append',
                        dest='attach',
                        help='Filename(s) to be attached.')

    parser.add_argument('-b',
                        '--body',
                        nargs='?',
                        type=FileType('r'),
                        required=True,
                        dest='body',
                        help='Filename containing the body of the message.')

    parser.add_argument('-l',
                        '--log',
                        default='INFO',
                        required=False,
                        dest='log',
                        help='The logging level to be used.')

    parser.add_argument('-v',
                        '--version',
                        action='version',
                        version='%(prog)s {}'.format(__version__))

    args = parser.parse_args()

    try:
        loglevel = nameToLevel[args.log.upper()]
    except Exception as e:
        print('Invalid log level: {}'.format(args.log))
        print('Please use one of the following values:')
        print('   * CRITICAL')
        print('   * ERROR')
        print('   * WARNING')
        print('   * INFO')
        print('   * DEBUG')
        print('   * NOTSET')
        exit()

    return args


if __name__ == "__main__":
    arguments = init()

    mailer = Emailer(loglevel=nameToLevel[arguments.log.upper()])

    disable_warnings(InsecureRequestWarning)

    mailer.send_msg_attachment(to=arguments.to,
                               subject=arguments.subject,
                               body=arguments.body.read(),
                               infile=arguments.attach,
                               deliver=True)
