#########################################
# Install Clair scripts in the directory
#########################################
- name: Create target folder
  file:
    path: /home/ubuntu/security-scan
    state: directory

- name: Distribute shell script file
  template: src=templates/container-scan.sh.j2 dest=/home/ubuntu/security-scan/container-scan.sh mode=0744

- name: Distribute printing results script file
  template: src=templates/print_results.sh.j2 dest=/home/ubuntu/security-scan/print_result.sh mode=0744

# for the execution of QuantumLeap, we need to increase the size... sysctl -w vm.max_map_count=262144
- name: Increase max virtual memory areas vm.max_map_count
  shell: sysctl -w vm.max_map_count=262144

#- name: Execute the script
#  shell: ./container-scan.sh
#  args:
#    chdir: /home/ubuntu/security-scan/

# - name: Get owner email detail from Docker Image's LABELS

# - name: Send notification to the owner
